config/routes.rb
MoviesWithFriends::Application.routes.draw do
  
  devise_for :users
  resources :home
  resources :users, only: [:index, :show]
  resources :events
  resources :movies
  resources :attendees, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

  root 'home#index'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :attendee, :class_name => "User"
  belongs_to :event_attending, :class_name => "Event"

  validates :attendee_id, uniqueness: {scope: :event_attending_id, message: "you are already going to this event"}

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator
  
  has_many :movies, :dependent => :destroy
  has_many :attendees, :dependent => :destroy


  dateFormatValidation = /\d\d\/\d\d\/\d\d/

  validates :event_name, presence: true
  validates :event_date, format: {with: dateFormatValidation}
  validates :vote_end_time, format: {with: dateFormatValidation}
  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :liker, :class_name => "User"
  belongs_to :liked, :class_name => "Movie"


  validates :liker_id, uniqueness: {scope: :liked_id, message:"you already liked this movie"}


end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :event

  dateFormatValidation = /\d\d\/\d\d\/\d\d/


  validates :title, presence: true, uniqueness: true
  validates :release_date, format: {with: dateFormatValidation}
  #validates :description, length: {within: 1000..1500}




end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #has_many :events, :dependent => :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :authenticate_user!

  #before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up){|u| u.permit(:name, :email, :password, :password_confirmation)}
  	devise_parameter_sanitizer.for(:account_update){|u| u.permit(:name, :email, :password, :password_confirmation)}
  end



end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

	def create
		@attendee = Attendee.new(attendee_params)
		if @attendee.save
			if current_user.id != @attendee.attendee.id
				Notifications.attended(@attendee).deliver
			end
			redirect_to events_path
		else
			redirect_to events_path
		end
	end

	def attendee_params
		params.require(:attendee).permit(:attendee_id, :event_attending_id)
	end

	def destroy
		@attendee = Attendee.find(params[:id])
		@attendee.destroy
		redirect_to events_path
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  	@event = Event.new
  end

  def create
  	@event = Event.new(event_params)
  	if @event.creator_id != current_user.id
      redirect_to 'new'
    else
      if @event.save
  		  redirect_to events_path
  	 else 
    		render 'new'
  	 end
    end
  end

  def event_params
  	params.require(:event).permit(:event_name, :event_date, :vote_end_time, :creator_id)
  end
  
  def index
  	@events = Event.all.order(:event_name)
  end

  def show
    @event = Event.find(params[:id])
    @attendees = Attendee.where(event_attending_id: @event.id)
    @attendees_id = []
    @attendees.each do |attend|
      @attendees_id.push(attend.attendee_id)
    end

    @users = User.where(id: @attendees_id).order(:name).limit(5)

    @movs = Movie.where(event_id: @event.id)
    @movs_id = []
    @movs.each do |mov|
      @movs_id.push(mov.id)
    end
    @movies_pre = Movie.where(id: @movs_id)
    @movies = @movies_pre.sort {|a, b| Like.where("liked_id = ?",b).count <=> Like.where("liked_id = ?", a).count}
    #@movies = @movies_pre.sort_by {|a| Like.where("liked_id = ?", a).count}

  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.creator_id != current_user.id
      render 'edit'
    else
      if @event.update_attributes(event_params)
        redirect_to event_path(@event.id)
      else 
        render 'edit'
      end
    end
  end


  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


	def create
		@like = Like.new(like_params)
		if @like.save
			#Notifications.attended(@like).deliver
			redirect_to movies_path
		else
			redirect_to movies_path
		end
	end

	def like_params
		params.require(:like).permit(:liker_id, :liked_id)
	end

	def destroy
		@like = Like.find(params[:id])
		@like.destroy
		redirect_to movies_path
	end


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
  	@movie = Movie.new
  end

  def create
  	@movie = Movie.new(movie_params)
  	if @movie.save
      Notifications.new_movie(@movie).deliver
  		redirect_to movies_path
  	else 
  		render 'new'
  	end
  end

  def movie_params
  	params.require(:movie).permit(:title, :release_date, :description, :event_id)
  end

  def index
  	@movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @movieEvent = Event.find(@movie.event_id)
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie.id)
    else 
      render 'edit'
    end
  end


  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def user_params
  	params.require(:user).permit(:name, :email, :password)
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to users_path
  	else 
  		render 'new'
  	end
  end

  def index
  	@users = User.all.order(:name)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user.id)
    else 
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_helper.rb
module AttendeeHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="error-msg">
	<% if @event.errors.any? %>
	<ul>
		<% @event.errors.full_messages.each do |msg| %>
		<li>
			<%=msg %>
		</li>
		<% end %>
	</ul>
	<% end %>
</div>

<%=form_for(@event) do |f| %>
	<div class="field">
		<p>Event Name</p>
		<%=f.text_field :event_name%>
	</div>
	<div class="field">
		<p>Event Date (mm/dd/yy)</p>
		<%=f.text_field :event_date%>
	</div>
	<div class="field">
		<p>End of Voting Time (mm/dd/yy)</p>
		<%=f.text_field :vote_end_time%>
	</div>
	<div class="field">
		<%=f.hidden_field :creator_id, :value=>current_user.id%>
	</div>

	<div class="actions">
		<%=f.submit %>
	</div>
<% end %>

<%=link_to "Home menu", home_index_path%>

app/views/events/index.html.erb
<table>
	<tr>
		<td>Event Name</td>
		<td>Event Date</td>
		<td>End of Voting Time</td>
		<td>Creator</td>
	</tr>
	<%@events.each do |event|%>
	<tr>
		<td><%=link_to event.event_name, event_path(event.id)%></td>
		<td><%=event.event_date%></td>
		<td><%=event.vote_end_time %></td>
		<td><%=User.find(event.creator_id).name%></td>

		<% if current_user.id == event.creator_id%>
		<td><%=link_to "edit event", edit_event_path(event.id)%></td>
		<td><%=button_to "delete event", event, :confirm => "Do you really want to delete this event?", method: :delete%></td>
		<% end %>

		<% if Attendee.where("attendee_id =? AND event_attending_id =?", current_user.id, event.id).empty?%>
			<td>
				<%=form_for(Attendee.new) do |f| %>
					<div class="field">
						<%=f.hidden_field :attendee_id, :value => current_user.id%>
					</div>
				
					<div class="field">
						<%=f.hidden_field :event_attending_id, :value => event.id%>
					</div>

					<div class="actions">
						<%=f.submit "attend"%>
					</div>

				<%end%>
			</td>
		<%else%>
			<td><%=button_to "unattend", Attendee.where("attendee_id = ? AND event_attending_id = ?", current_user.id, event.id).take!, method: :delete%></td>
		<%end%>

	</tr>

	<% end %>

	<tr>

		<td>attendee</td>
		<td>event</td>
		<%Attendee.all.each do |attend|%>
			<tr>
				<td><%=attend.attendee.name%></td>
				<td><%=attend.event_attending.event_name%></td>

			</tr>
		<%end%>

	</tr>

</table>

<%=link_to "new event", new_event_path%>
<%=link_to "Home menu", home_index_path%>

app/views/events/new.html.erb
<div class="error-msg">
	<% if @event.errors.any? %>
	<ul>
		<% @event.errors.full_messages.each do |msg| %>
		<li>
			<%=msg %>
		</li>
		<% end %>
	</ul>
	<% end %>
</div>

<%=form_for(@event) do |f| %>
	<div class="field">
		<p>Event Name</p>
		<%=f.text_field :event_name%>
	</div>
	<div class="field">
		<p>Event Date (mm/dd/yy)</p>
		<%=f.text_field :event_date%>
	</div>
	<div class="field">
		<p>End of Voting Time (mm/dd/yy)</p>
		<%=f.text_field :vote_end_time%>
	</div>
	<div class="field">
		<%=f.hidden_field :creator_id, :value=>current_user.id%>
	</div>

	<div class="actions">
		<%=f.submit %>
	</div>
<% end %>

<%=link_to "Home menu", home_index_path%>

app/views/events/show.html.erb
<div>
	<h2><%=@event.event_name%></h2>
	<p>Event date:  <%=@event.event_date%></p>
	<p>Voting period ends:  <%=@event.vote_end_time%></p>
	<p>Creator is:  <%=User.find(@event.creator_id).name%></p>
	<% if current_user.id == @event.creator_id%>
		<td><%=link_to "edit event", edit_event_path(@event.id)%></td>
		<td><%=button_to "delete event", @event, :confirm => "Do you really want to delete this event?", method: :delete%></td>
	<% end %>

	<div class="attend">
		<p>Some Attendees include</p>
		<p>
			<% @users.each do |user|%>
				<%=user.name%>, 
			<%end%>
		</p>
	</div>

	<button class="btn">Hide Attending Users</button>

	<p>Movies to vote on</p>

	<p>
		<% @movies.each do |mov|%>
			<%=mov.title%>, 
		<%end%>
	</p>

	<%=link_to "index", events_path%>
	<%=link_to "Home menu", home_index_path%>


</div>

app/views/home/index.html.erb
<title>
	Movies With Friends!
</title>

<head>
	<h1> Welcome To Movies With Friends</h1>
</head>

<body>

	<p>Users</p>
	<!--<%=link_to "new users", new_user_session_path%>-->
	<%=link_to "edit user", edit_user_registration_path%>
	<%=link_to "view profile", user_path(current_user.id)%>
	<%=link_to "all users", users_path%>


	<p>Events</p>
	<%=link_to "new event", new_event_path%>
	<%=link_to "all events", events_path%>

	<p>Movies</p>
	<%=link_to "new movie", new_movie_path%>
	<%=link_to "all movies", movies_path%>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoviesWithFriends</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<p class="notice"><%=notice%></p>
<p class="alert"><%=alert%></p>

<ul class="nav navbar-nav">
	<% if user_signed_in? %>
	<li>
		<%=link_to('Logout', destroy_user_session_path, :method => :delete)%>
	</li>
	<% else %>
	<li>
		<%=link_to('Login', new_user_session_path) %>
	</li>
	<% end %>
</ul>

</body>
</html>

app/views/movies/edit.html.erb
<div class="error-msg">
	<% if @movie.errors.any? %>
	<ul>
		<% @movie.errors.full_messages.each do |msg| %>
		<li>
			<%=msg %>
		</li>
		<% end %>
	</ul>
	<% end %>
</div>

<%=form_for(@movie) do |f| %>
	<div class=”field”>
		<p>Title</p>
		<%=f.text_field :title %>
	</div>
	<div class=”field”>
		<p>Release Date (mm/dd/yy)</p>
		<%=f.text_field :release_date %>
	</div>

	<div class="field">
		<p>Description</p>
		<%=f.text_area :description %>
	</div>

	<div class=”field”>
		<p>Event</p>
		<%=f.collection_select :event_id, Event.all, :id, :event_name %>
	</div>
	<div class=”actions”>
		<%=f.submit %>
	</div>
<% end %>

<%=link_to "Home menu", home_index_path%>

app/views/movies/index.html.erb
<table>
	<tr>
		<td>Title</td>
		<td>Release Date</td>
		<td>Event</td>
	</tr>
	<%@movies.each do |movie|%>

	<%if !Attendee.where("attendee_id =? AND event_attending_id =?", current_user.id, movie.event.id).empty?%>
			<tr>
			<td><%=link_to movie.title, movie_path(movie.id)%></td>
			<td><%=movie.release_date %></td>
			<td><%=Event.find(movie.event_id).event_name %></td>
			<td><%=link_to "edit movie", edit_movie_path(movie.id)%></td>
			<td><%=button_to "delete movie", movie, confirm:"Do you really want to delete this movie?", method: :delete%></td>
	
			<% if Date.strptime(Event.find(movie.event_id).vote_end_time, "%m/%d/%Y").strftime("%m/%d/%Y") > Date.today.strftime("%m/%d/%Y")%>



				<% if Like.where("liker_id =? AND liked_id =?", current_user.id, movie.id).empty?%>
					<td>
						<%=form_for(Like.new) do |f| %>
							<div class="field">
								<%=f.hidden_field :liker_id, :value => current_user.id%>
							</div>
				
							<div class="field">
								<%=f.hidden_field :liked_id, :value => movie.id%>
							</div>

							<div class="actions">
								<%=f.submit "like"%>
							</div>
						<%end%>
					</td>
				<%else%>
					<td><%=button_to "unlike", Like.where("liker_id = ? AND liked_id = ?", current_user.id, movie.id).take!, method: :delete%></td>
				<%end%>
			<%end%>
			</tr>
		<% end %>
	<%end%>


	<tr>

		<td>Likers</td>
		<td>Movie</td>
		<%Like.all.each do |like|%>
			<tr>
				<td><%=like.liker.name%></td>
				<td><%=like.liked.title%></td>

			</tr>
		<%end%>

	</tr>



</table>


<%=link_to "new movie", new_movie_path%>
<%=link_to "Home menu", home_index_path%>

app/views/movies/new.html.erb
<div class="error-msg">
	<% if @movie.errors.any? %>
	<ul>
		<% @movie.errors.full_messages.each do |msg| %>
		<li>
			<%=msg %>
		</li>
		<% end %>
	</ul>
	<% end %>
</div>

<h1>You must be attending an event before you create a movie for it!</h1>

<%=form_for(@movie) do |f| %>
	<div class="field">
		<p>Title</p>
		<%=f.text_field :title %>
	</div>
	<div class="field">
		<p>Release Date (mm/dd/yy)</p>
		<%=f.text_field :release_date %>
	</div>

	<div class="field">
		<p>Description</p>
		<%=f.text_area :description %>
	</div>

	<div class="field">
		<p>Event</p>
		<%=f.collection_select :event_id, Event.all, :id, :event_name %>
	</div>

	<div class="actions">
		<%=f.submit %>
	</div>
<% end %>

<%=link_to "Home menu", home_index_path%>

app/views/movies/show.html.erb
<div>
	<h2><%=@movie.title%></h2>
	<p>Release Date: <%=@movie.release_date%></p>
	<p>Number of votes = <%=Like.where("liked_id = ?", @movie.id).count%></p>
	<p>Description: <%=@movie.description%></p>
	<p>Event name: <%=@movieEvent.event_name%></p>
	<%=link_to "edit movie", edit_movie_path(@movie.id)%>
	<%=link_to "index", movies_path%>
	<%=link_to "Home menu", home_index_path%>
</div>

app/views/notifications/attended.html.erb
<h2><%=@greeting%></h2>

<p><%=@attendee%> says that they are coming to your event!  Maybe it's time to start seriously planning?  It'll be a great party with <%=@attendee%> around, won't it?
</p>
<p>
  Make updates to your event, <%=@eventtitle%>, <a href=<%event_url(@eventid)%>>here</a>.
</p>
<p>
  You can also check out <%=@attendee%>'s profile <a href=<%=user_url(@id)%>>here</a>.
</p>

app/views/notifications/new_movie.text.erb
<%= @greeting %> <%= @event_creator %>, <%=@movie_name%> was just added to your event <%= @event %>!  Why don't you go take a look? The link is <%= movie_url(@id)%>

app/views/users/edit.html.erb
<%=form_for(@user) do |f| %>
	<div class=”field”>
		<p>name</p>
		<%=f.text_field :name %>
	</div>
	<div class=”field”>
		<p>email</p>
		<%=f.text_field :email %>
	</div>
	<div class=”field”>
		<p>password</p>
		<%=f.text_field :password %>
	</div>
	<div class=”actions”>
		<%=f.submit %>
	</div>
<% end %>

app/views/users/index.html.erb
<table>
	<tr>
		<td>name</td>
		<td>email</td>
		<td>password</td>
	</tr>
	<%@users.each do |user|%>
	<tr>
		<td><%=link_to user.name, user_path(user.id)%></td>
		<td><%=user.email %></td>
		<td><%=user.password %></td>
		<%if current_user.id == user.id%>
		<td><%=link_to "edit profile", edit_user_registration_path%></td>
		<td><%=button_to "delete profile", user, confirm:"Do you really want to delete your profile?", method: :delete%></td>
		<%end%>

	</tr>
	<% end %>
</table>

<%=link_to "Home menu", home_index_path%>

app/views/users/new.html.erb
<%=form_for(@user) do |f| %>
	<div class=”field”>
		<p>name</p>
		<%=f.text_field :name %>
	</div>
	<div class=”field”>
		<p>email</p>
		<%=f.text_field :email %>
	</div>
	<div class=”field”>
		<p>password</p>
		<%=f.text_field :password %>
	</div>
	<div class=”actions”>
		<%=f.submit %>
	</div>
<% end %>

app/views/users/show.html.erb
<div>
	<h2><%=@user.name%></h2>
	<p><%=@user.email%></p>
	<p><%=@user.password%></p>
	<%=link_to "edit user", edit_user_registration_path(@user.id)%>
	<%=link_to "index", users_path%>

</div>